# Generated by Django 4.0.5 on 2022-06-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_carrito_preciosub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='precioSub',
        ),
    ]
