# Generated by Django 4.0.5 on 2022-06-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_suscriptor_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='esta_comprado',
            field=models.BooleanField(default=False),
        ),
    ]
