# Generated by Django 4.0.5 on 2022-06-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_carrito_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscriptor',
            name='username',
        ),
        migrations.AddField(
            model_name='suscriptor',
            name='email',
            field=models.EmailField(default=1, max_length=254, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
