# Generated by Django 4.0.5 on 2022-06-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_suscriptor_username_suscriptor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='esta_comprado',
        ),
        migrations.AddField(
            model_name='carrito',
            name='precioSub',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
