# Generated by Django 4.0.5 on 2022-06-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_carrito_esta_comprado_carrito_preciosub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('precioSub', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='productos_carrito')),
                ('usuario', models.IntegerField()),
            ],
        ),
    ]
