# Generated by Django 4.0.5 on 2022-06-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_carrito_usuario_alter_seguimiento_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='estado',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estadopedido',
            name='estado',
            field=models.CharField(max_length=60),
        ),
    ]
