# Generated by Django 4.0.5 on 2022-06-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_seguimiento_estado_alter_estadopedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
